- name: Workflow output'tan cihazları al ve ServiceCore’a gönder
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    servicecore_api_url: "{{ servicecore_api_url }}"
    servicecore_api_key: "{{ servicecore_api_key }}"
    asset_status_id: "{{ asset_status_id }}"
    asset_type_id: "{{ asset_type_id }}"

  tasks:
    - name: Fetch Devices çıktısından cihazları al
      set_fact:
        device_names: "{{ hostvars['localhost']['shared_device_names'] }}"

    - name: Her cihazı ServiceCore'a gönder
      uri:
        url: "{{ servicecore_api_url }}"
        method: POST
        headers:
          ApiKey: "{{ servicecore_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          assetStatusId: "{{ asset_status_id }}"
          name: "{{ item }}"
          assetTypeId: "{{ asset_type_id }}"
        status_code: 200
      loop: "{{ device_names }}"
      loop_control:
        label: "{{ item }}"




