- name: Dosyadan cihazları oku ve ServiceCore’a gönder
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    servicecore_api_url: "https://apiegitimlab.servicecore.app/api/v1/Asset/Create"
    servicecore_api_key: "4y1PUHOHeGpVaERoo5saZD8ciqn94VpZjJK7ygOOCiE="
    input_file: "/tmp/device_list.json"

  tasks:
    - name: Cihaz listesi dosyasını oku
      slurp:
        src: "{{ input_file }}"
      register: file_data

    - name: JSON olarak ayrıştır
      set_fact:
        device_names: "{{ file_data['content'] | b64decode | from_json }}"

    - name: Her cihazı ServiceCore'a gönder
      uri:
        url: "{{ servicecore_api_url }}"
        method: POST
        headers:
          ApiKey: "{{ servicecore_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          assetStatusId: 1
          name: "{{ item }}"
          assetTypeId: 1
        status_code: 200
      loop: "{{ device_names }}"
      loop_control:
        label: "{{ item }}"




