---
- name: Fetch devices from external API
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    api_url_devices: "https://213.153.197.248:8585/api/1.0/devices/"
    api_auth_header: "Basic YWRtaW46QWExMjM0NTYu"

  tasks:
    - name: Get device list from external API
      uri:
        url: "{{ api_url_devices }}"
        method: GET
        headers:
          Authorization: "{{ api_auth_header }}"
        return_content: yes
        validate_certs: no
      register: devices_response

    - name: Set device list as fact (output)
      set_fact:
        device_list: "{{ devices_response.json.Devices }}"

    - name: Show device list for debug (optional)
      debug:
        var: device_list


