- name: AWX Variables ile gelen değerleri kullan
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Gelen test1 değerini göster
      debug:
        msg: "test1: {{ test1 }}"

    - name: Gelen test2 değerini göster
      debug:
        msg: "test2: {{ test2 }}"

    - name: Gelen test3 değerini göster
      debug:
        msg: "test3: {{ test3 }}"

    - name: (İsteğe bağlı) Tüm input'ları bir API'ye gönder
      uri:
        url: "https://postman-echo.com/post"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          input_1: "{{ test1 }}"
          input_2: "{{ test2 }}"
          input_3: "{{ test3 }}"
        status_code: 200
      register: result

    - name: API yanıtını göster
      debug:
        var: result.json

