- name: Dışarıdan alınan input ile basit test
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    custom_input: "{{ custom_input }}"  # Dışarıdan alınan input burada

  tasks:
    - name: Girilen değeri göster
      debug:
        msg: "Flow’un çıktısı: {{ custom_input }}"

    - name: (İsteğe bağlı) API'ye bu değeri gönder
      uri:
        url: "https://postman-echo.com/post"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          input_value: "{{ custom_input }}"
        status_code: 200
      register: result

    - name: API yanıtını göster
      debug:
        var: result.json

