---
- name: Sunucu Kontrolü
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping testi
      ping:

    - name: Uptime bilgisi
      command: uptime

    - name: Disk kontrolü
      command: df -h
