- name: Dış API’den cihaz listesini çek ve varlık oluştur
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    api_url_devices: "{{ api_url_devices }}"
    api_auth_header: "{{ api_auth_header }}"
    api_url_create_asset: "{{ api_url_create_asset }}"
    api_key_create_asset: "{{ api_key_create_asset }}"

  tasks:
    - name: Cihaz listesini dış API'den çek
      uri:
        url: "{{ api_url_devices }}"
        method: GET
        headers:
          Authorization: "{{ api_auth_header }}"
        return_content: yes
        validate_certs: no
      register: devices_response

    - name: Cihaz isimlerini ayıkla
      set_fact:
        device_names: "{{ devices_response.json.Devices | map(attribute='name') | list }}"

    - name: Her cihaz için varlık oluştur
      uri:
        url: "{{ api_url_create_asset }}"
        method: POST
        headers:
          ApiKey: "{{ api_key_create_asset }}"
          Content-Type: "application/json"
        body_format: json
        body:
          assetStatusId: 1
          name: "{{ item }}"
          assetTypeId: 1
        status_code: 201
      loop: "{{ device_names }}"
