- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Cihaz listesini API'den çek
      uri:
        url: https://213.153.197.248:8585/api/1.0/devices/
        method: GET
        headers:
          Authorization: "Basic YWRtaW46QWExMjM0NTYu"
        return_content: yes
        validate_certs: no
      register: devices_response

    - name: API cevabını debug ile yazdır
      debug:
        var: devices_response.json

    - name: Cihaz isimlerini liste olarak ayıkla
      set_fact:
        device_names: "{{ devices_response.json.Devices | map(attribute='name') | list }}"
      failed_when: device_names is not defined

    - name: Her cihaz için varlık oluştur
      uri:
        url: https://apiegitimlab.servicecore.app/api/v1/Asset/Create
        method: POST
        headers:
          ApiKey: "4y1PUHOHeGpVaERoo5saZD8ciqn94VpZjJK7ygOOCiE="
          Content-Type: "application/json"
        body_format: json
        body:
          assetStatusId: 1
          name: "{{ item }}"
          assetTypeId: 1
        status_code: 200
      loop: "{{ device_names }}"


